name: tierrating

services:
  api:
    image: ghcr.io/ratzzfatzz/tierrating-api:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      SECRET_KEY: ${SECRET_KEY:?secret key can't be empty}
      TOKEN_EXPIRATION: ${TOKEN_EXPIRATION:-80}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_USERNAME: ${DB_USERNAME:-tierrating}
      DB_PASSWORD: ${DB_PASSWORD:?database password can't be empty}
      ANILIST_CLIENT_KEY: ${ANILIST_CLIENT_KEY}
      ANILIST_CLIENT_SECRET: ${ANILIST_CLIENT_SECRET}
      ANILIST_REDIRECT_URL: ${ANILIST_REDIRECT_URL}
      TRAKT_CLIENT_KEY: ${TRAKT_CLIENT_KEY}
      TRAKT_CLIENT_SECRET: ${TRAKT_CLIENT_SECRET}
      TRAKT_REDIRECT_URL: ${TRAKT_REDIRECT_URL}
      TMDB_API_KEY: ${TMDB_API_KEY}
      STEAM_API_KEY: ${STEAM_API_KEY}

  ui:
    image: ghcr.io/ratzzfatzz/tierrating-web:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      API_URL: ${API_URL:-http://api:8080}

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DB_USERNAME:-tierrating}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?database password can't be empty}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-tierrating} -d tierrating"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
