GET http://localhost:8080/anilist/RatzzFatzz/anime
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJSYXR6ekZhdHp6IiwiaWF0IjoxNzUzNjUyNTk1LCJleHAiOjE3NTM2NTYxOTV9.rwPJLj5tuks85VYYP1awv8zXQgqrePaDSim44Lfd35w

###

GET http://localhost:8080/anilist/RatzzFatzzarst

###

POST http://localhost:8080/anilist/auth/RatzzFatzz
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJSYXR6ekZhdHp6IiwiaWF0IjoxNzQ5NDk4NTIyLCJleHAiOjE3NDk1MDIxMjJ9.CclOjwUv7lNfRD5jHAIM-PskV2yAO-dgyZ-B0DpO6Bg
Content-Type: application/json

{
  "code": "<code>"
}

###

POST https://anilist.co/api/v2/oauth/token
Content-Type: application/json
Accept: application/json

{
  "grant_type": "authorization_code",
  "client_id": "<client_code>",
  "client_secret": "<client_secret>",
  "redirect_uri": "http://localhost:3000/auth/anilist",
  "code": "<code>>"
}

###

GRAPHQL https://graphql.anilist.co

query userExists($name: String) {
    User(name: $name) {
        id
        name
    }
}

{
  "name": "ratzzfatzz"
}

###

GRAPHQL https://graphql.anilist.co

query ExampleQuery($userName: String, $type: MediaType, $status: MediaListStatus, $page: Int, $perPage: Int) {
    Page(page: $page, perPage: $perPage) {
        pageInfo {
            currentPage
            hasNextPage
            perPage
        }
        mediaList(userName: $userName, type: $type, status: $status) {
            score(format: POINT_10)
            media {
                id
                title {
                    romaji
                    english
                    native
                }
                coverImage {
                    large
                    extraLarge
                }
            }
        }
    }
}


{
  "userName": "ratzzfatzz",
  "status": "COMPLETED",
  "type": "ANIME",
  "page": 1,
  "perPage": 500
}

###
POST localhost:8080/data/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJSYXR6ekZhdHp6IiwiaWF0IjoxNzYwOTk2MzQzLCJleHAiOjE3NjA5OTk5NDN9.ZLH8OpUJvvP9HOJ-KG2o6jHnc-JQhyLOn8GgU-stdKU
Content-Type: application/json

{
  "id": "11111",
  "rating": "10",
  "username": "RatzzFatzz",
  "service": "ANILIST"
}