### Signup
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "username": "admin",
    "email": "testing@tierrating.com",
    "password": "arstarst"
}

### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "arstarst"
}

### Change Password
POST http://localhost:8080/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJSYXR6ekZhdHp6IiwiaWF0IjoxNzYyODkwNTM1LCJleHAiOjE3NjI4OTQxMzV9.t1g9seJgqn9TpcH-O1gfDz-f4IIuvpJj5dnAvIByqnw

{
  "username": "RatzzFatzz",
  "oldPassword": "arstarst",
  "newPassword": "arstarstarst"
}

### Delete account
POST http://localhost:8080/auth/delete-account
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2MjkwOTc0MiwiZXhwIjoxNzYyOTEzMzQyfQ.yap8-DEeV5Bn4TXpihySLVeujJblDc5LXWnd88qrhXM

{
  "username": "admin"
}