### GET tiers for anilist anime
GET http://localhost:8080/tiers/RatzzFatzz/anilist/anime
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJSYXR6ekZhdHp6IiwiaWF0IjoxNzU4MjE4MTYzLCJleHAiOjE3NTgyMjE3NjN9.StYCWvtgBGMtJROhh4kx_T6h7s8SSmgcccg4cxSzhUk
Content-Type: application/json

###